name: ast_explorer_cli
description: A Command-Line Interface for explorer flutter/dart simplified ast.
version: 0.2.0
homepage: https://github.com/lsaudon/ast_explorer_cli
repository: https://github.com/lsaudon/ast_explorer_cli
issue_tracker: https://github.com/lsaudon/ast_explorer_cli/issues

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  analyzer: ^5.13.0
  args: ^2.4.1
  cli_completion: ">=0.3.0 <0.5.0"
  collection: ^1.17.2
  equatable: ^2.0.5
  file: ^6.1.4 # pub_updater want 6.1.4
  mason_logger: ^0.2.6
  path: ^1.8.3
  pub_updater: ^0.3.0

dev_dependencies:
  build_runner: ^2.4.4
  build_verify: ^3.1.0
  build_version: ^2.1.1
  mocktail: ^0.3.0
  test: ^1.24.3

executables:
  ast_explorer:
