name: ast_explorer_cli
description: A Command-Line Interface for explorer flutter/dart simplified ast.
version: 0.2.0
homepage: https://github.com/lsaudon/ast_explorer_cli
repository: https://github.com/lsaudon/ast_explorer_cli
issue_tracker: https://github.com/lsaudon/ast_explorer_cli/issues

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  analyzer: ^6.2.0
  args: ^2.4.2
  cli_completion: ^0.4.0
  collection: ^1.18.0
  equatable: ^2.0.5
  file: ^7.0.0
  mason_logger: ^0.2.10
  path: ^1.8.3
  pub_updater: ^0.4.0

dev_dependencies:
  build_runner: ^2.4.6
  build_verify: ^3.1.0
  build_version: ^2.1.1
  mocktail: ^1.0.1
  test: ^1.24.7

executables:
  ast_explorer:
